/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package GraddleApp;

 import static org.junit.Assert.assertArrayEquals;
import static org.junit.Assert.assertThat;

import org.hamcrest.Matcher;
import org.hamcrest.core.Is;
import org.hamcrest.core.IsEqual;
import org.junit.Test;
import org.openqa.selenium.By;
 import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.PageFactory;
import org.openqa.selenium.WebDriver;

public class App {

    @Test
    public static void main(String[] args) {
    }
}